// Editorial metadata shared by the HTML and the downloadable AI proposal catalogue.
// These are selection criteria, not measured performance or generated AI scores.
export const editorial = {
  face: {tags:['Nouvelle idée','Changement d’angle','Pédagogie'], tone:'Discret', needs:['Visage visible dans A et B','Regards et tailles de visage compatibles'], favor:'Deux phrases liées, avec un nouvel argument ou un changement d’angle.', avoid:'Visage masqué, axe très différent ou révélation qui mérite une rupture forte.'},
  gesture: {tags:['Démonstration','Énumération','Continuité du geste'], tone:'Naturel', needs:['Geste visible des deux côtés','Direction et phase du geste compatibles'], favor:'Le mouvement de la main accompagne une explication et traverse la coupe.', avoid:'Mains immobiles, gestes opposés ou coupure au milieu d’une action illisible.'},
  hand: {tags:['Changement de sujet','Révélation','Ellipse'], tone:'Joueur', needs:['Main isolable ou geste couvrant l’objectif','Couverture suffisante au moment du raccord'], favor:'Une main masque le plan pour annoncer un nouveau sujet ou dévoiler le résultat.', avoid:'Tonalité solennelle ou geste artificiel sans rapport avec le discours.'},
  peel: {tags:['Avant / après','Changement de ton','Comparaison'], tone:'Graphique', needs:['Silhouette détourable','Place pour le déplacement latéral'], favor:'On quitte une ancienne version, une erreur ou un état pour montrer son contraire.', avoid:'Geste de précision à conserver ou silhouette difficile à isoler.'},
  echo: {tags:['Punchline','Réaction','Insistance'], tone:'Énergique', needs:['Pose ou geste expressif','Silhouette détourable'], favor:'Une réaction, une phrase percutante ou une insistance brève sur un geste.', avoid:'Information dense à lire ou accumulation d’effets déjà présents.'},
  word: {tags:['Mot clé','Point à retenir','Chiffre fort'], tone:'Pédagogique', needs:['Mot ou chiffre vérifié dans la transcription','Espace lisible pour le texte'], favor:'Le raccord coïncide avec le terme central que le spectateur doit retenir.', avoid:'Mot inventé, texte long, sous-titres concurrents ou visage essentiel masqué.'},
  blink: {tags:['Raccord discret','Respiration','Coupe de silence'], tone:'Invisible', needs:['Clignement réel au raccord','Position du visage compatible entre A et B'], favor:'Une pause ou une coupe de silence pendant la fermeture naturelle des paupières.', avoid:'Absence de clignement ou action importante pendant la coupe.'},
  lag: {tags:['Révélation','Changement de contexte','Contraste'], tone:'Surprenant', needs:['Silhouette détourable','Décor ou cadrage B visiblement différent'], favor:'Le contexte change avant que la personne ne réagisse : contraste ou nouvelle réalité.', avoid:'Deux plans presque identiques ou passage exigeant une continuité réaliste.'},
  portal: {tags:['Transformation','Projection','Retour au réel'], tone:'Immersif', needs:['Contour de personne exploitable','Contenu A / B qui justifie un passage'], favor:'IN : entrer dans une idée, une promesse ou une transformation. OUT : sortir de cet état, revenir au réel ou révéler le contexte.', avoid:'Raccord factuel banal, contours coupés ou ton qui exclut une métaphore visuelle.', variants:[{id:'in',name:'IN · Entrer',tags:['Transformation','Projection','Promesse'],use:'La photo détourée de B grandit dans le plan A, puis B remplit le cadre.'},{id:'out',name:'OUT · Sortir',tags:['Retour au réel','Fin de parenthèse','Révélation du contexte'],use:'La photo détourée de A rétrécit et disparaît devant le plan B.'}]},
  glass: {tags:['Déclic','Prise de conscience','Retournement'], tone:'Sensoriel', needs:['Visage visible et point de départ lisible','Déformation passagère du visage acceptable'], favor:'Une phrase change la perception du sujet : déclic, contradiction ou révélation.', avoid:'Détail à lire, démonstration précise ou exigence de préserver le visage sans déformation.'},
  gravity: {tags:['Chute','Conclusion','Renversement'], tone:'Spectaculaire', needs:['Silhouette détourable','Espace pour une sortie verticale'], favor:'Chute humoristique, conclusion forte ou renversement explicite de la situation.', avoid:'Passage intime ou solennel, conclusion douce ou effet spectaculaire juste avant.'}
};

export function aiCatalogue(transitions, renderer) {
  return {
    version:1,
    purpose:'Évaluer chaque proposition de transition dans son contexte de montage.',
    scoreMeaning:'Pourcentage de pertinence éditoriale, pas une probabilité de viralité. Distinct de l’intensité visuelle.',
    input:{context:['transcription avant / après avec timecodes','intention narrative','ton','observations visuelles A / B','gestes et clignements détectés','qualité du détourage','effets voisins et intervalle depuis le dernier effet'],proposals:['proposalId','transitionId','variant','cutTime','intensityPercent','durationFrames','paper','borderWidthPx','roughness','monochrome']},
    evaluation:{weights:{narrative:40,visual:30,tone:20,rhythm:10},formula:'Arrondir 0.40 × narrative + 0.30 × visual + 0.20 × tone + 0.10 × rhythm ; chaque sous-score est compris entre 0 et 100.',rules:['Évaluer indépendamment chaque proposition ; ne pas normaliser la somme des scores à 100.','Précondition requise absente : status = ineligible, scorePercent = 0, expliquer le motif.','Précondition requise inconnue ou contexte insuffisant : status = needs_context, scorePercent = null, lister les éléments manquants.','Sinon status = scored ; justifier le score avec des éléments fournis, sans inventer un geste ou une intention.','Évaluer la variante, la durée, l’intensité et le papier proposés ; une intensité excessive réduit la pertinence selon le ton et le rythme.','Le papier déchiré convient aux passages graphiques, ludiques ou de collage ; réduire la pertinence pour un passage sobre ou intime.','À 0 % d’intensité, évaluer une coupe franche ; les préconditions propres aux effets visuels désactivés ne s’appliquent plus.','Ne pas interpréter le score comme un gain de rétention mesuré.']},
    outputContract:{results:[{proposalId:'identifiant reçu',transitionId:'identifiant reçu',variant:'in | out | null',status:'scored | ineligible | needs_context',scorePercent:'entier 0..100 ou null',subscores:'narrative, visual, tone, rhythm : 0..100 ; null si non évaluables',reason:'justification courte fondée sur le passage',missingContext:['informations nécessaires absentes']}]},
    transitions:transitions.map(t=>({id:t.id,name:t.name,originalConcept:!!t.original,durationFrames:{min:t.minFrames,max:t.maxFrames,default:t.defaultFrames,current:t.frames},fps:30,...editorial[t.id],personTreatment:t.person,intensity:t.intensityTarget?{min:0,max:150,default:100,controls:t.intensityTarget,current:Math.round(renderer.intensity(t.id)*100)}:null,paperCutout:['portal','gravity'].includes(t.id)?{supported:true,borderWidthPx:{min:0,max:40,default:24},roughness:{min:0,max:1,default:.7},current:renderer.style(t.id)}:null,physicsAt100Percent:t.physics,previewCaveat:t.note}))
  };
}
